### PR TITLE
Fixing extraneous open bracket

### PR DESCRIPTION
**Pull request by JALsnipe**
Fixed the issue addressed here: https://github.com/youtube/youtube-ios-player-helper/commit/0fabe5c60140bea38c458fd02e22bc06b108bea9#commitcomment-11620707

### CODE REVIEW

**Comment by kmiloaguilar** [comment]
lol did the same.

**Comment by bm-i** [comment]
:+1:

**Comment by JALsnipe** [comment]
@iulukaya please review and merge this quick typo fix.

**Comment by JALsnipe** [comment]
Thank you!

**Pull request merged**
